# Generated by Django 2.2.5 on 2019-09-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190911_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragon',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
